name: CI

on:
  pull_request:
    branches: [master]

jobs:
  run-test:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven test
        id: test
        run: mvn test
        continue-on-error: true

      - name: Check on failures
        if: steps.test.outcome != 'success'
        run: exit 1